#!/usr/bin/env node
/**
 * Pasang pre-commit di repo git saat ini (bukan global).
 *
 * Shim 0755 di .git/hooks/pre-commit:
 *   - kalau han.sip/cli.mjs ada di repo (kotak-kecil sendiri) → node lokal
 *   - kalau tidak (repo orang lain) → npx github:ganezha/kotak-kecil# + commit SHA
 *
 * Hook asing: cadangan ke pre-commit.bak (atau .bak.<epoch> kalau sudah ada),
 * lalu timpa. Bukan diam-diam. Bukan alasan git commit --no-verify.
 *
 * Manual. Jangan ikat ke npm prepare/postinstall — itu nulis .git
 * setiap npm install.
 *
 * Idempotent. --check untuk verifikasi.
 */
import { execFile } from "node:child_process";
import { realpathSync } from "node:fs";
import { chmod, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";

const execFileP = promisify(execFile);
export const HOOK_MARK = "generated by han.sip";
/** Commit yang berisi walk + detector. Bukan tag — tag bisa digeser. */
export const PIN_SHA = "16f0c992c0d2dbbc18d0310882cf577ff764cfb8";
export const NPX = `github:ganezha/kotak-kecil#${PIN_SHA}`;

export function hookBody() {
  return `#!/bin/sh
# ${HOOK_MARK} — jalankan lagi kalau file ini hilang
root="$(git rev-parse --show-toplevel)" || exit 2
if [ -f "$root/han.sip/cli.mjs" ]; then
  exec node "$root/han.sip/cli.mjs" --staged --quiet
fi
exec npx --yes ${NPX} -- --staged --quiet
`;
}

function isOurs(body) {
  return (
    body.includes(HOOK_MARK) ||
    body.includes(".githooks/pre-commit.mjs") ||
    body.includes("han.sip/cli.mjs")
  );
}

async function backupIfForeign(dest, existing) {
  if (!existing || isOurs(existing)) return null;
  let bak = `${dest}.bak`;
  try {
    await stat(bak);
    bak = `${dest}.bak.${Date.now()}`;
  } catch {
    /* first backup */
  }
  await writeFile(bak, existing, { encoding: "utf8", mode: 0o755 });
  return bak;
}

async function toplevel() {
  try {
    const { stdout } = await execFileP("git", ["rev-parse", "--show-toplevel"]);
    return stdout.trim();
  } catch (err) {
    if (err && err.code === "ENOENT") throw new Error("git tidak ada di PATH");
    throw new Error("bukan git repo");
  }
}

async function gitDir(root) {
  const { stdout } = await execFileP("git", ["rev-parse", "--git-dir"], {
    cwd: root,
  });
  return path.resolve(root, stdout.trim());
}

export async function pasang({ check = false } = {}) {
  const root = await toplevel();
  const dest = path.join(await gitDir(root), "hooks", "pre-commit");

  if (check) {
    let body = "";
    try {
      body = await readFile(dest, "utf8");
    } catch {
      console.error("han.sip pasang: hook belum ada");
      process.exit(1);
    }
    if (!isOurs(body)) {
      console.error("han.sip pasang: hook bukan punya kita");
      process.exit(1);
    }
    console.log("han.sip pasang: sip.");
    process.exit(0);
  }

  await mkdir(path.dirname(dest), { recursive: true });
  let existing = "";
  try {
    existing = await readFile(dest, "utf8");
  } catch {
    existing = "";
  }
  const bak = await backupIfForeign(dest, existing);
  if (bak) {
    console.warn(`han.sip pasang: hook asing. Cadangan: ${bak}`);
  }
  await writeFile(dest, hookBody(), { encoding: "utf8", mode: 0o755 });
  await chmod(dest, 0o755);
  console.log("han.sip pasang: pre-commit terpasang.");
}

function isCliEntry() {
  const arg = process.argv[1];
  if (!arg) return false;
  let resolved = arg;
  try {
    resolved = realpathSync(arg);
  } catch {
    /* argv[1] may be the npm symlink */
  }
  try {
    return (
      import.meta.url === pathToFileURL(resolved).href ||
      import.meta.url === pathToFileURL(arg).href
    );
  } catch {
    return false;
  }
}

if (isCliEntry()) {
  pasang({ check: process.argv.includes("--check") }).catch((err) => {
    console.error("han.sip pasang:", err.message);
    process.exit(2);
  });
}
