#!/usr/bin/env node
/**
 * Pasang pre-commit di repo ini saja (bukan global).
 *
 * Sumber hook (.githooks/pre-commit.mjs) ikut di-commit, tapi .git tidak.
 * File di git tree juga sering 0644, jadi kita tidak andalkan bit +x.
 * Yang dipasang: shim 0755 di .git/hooks/pre-commit → node .githooks/pre-commit.mjs
 *
 * Idempotent. --check untuk verifikasi.
 */
import { execFile } from "node:child_process";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const execFileP = promisify(execFile);
const MARKER = ".githooks/pre-commit.mjs";

async function toplevel() {
  try {
    const { stdout } = await execFileP("git", ["rev-parse", "--show-toplevel"]);
    return stdout.trim();
  } catch (err) {
    if (err && err.code === "ENOENT") throw new Error("git tidak ada di PATH");
    throw new Error("bukan git repo");
  }
}

async function gitDir(root) {
  const { stdout } = await execFileP("git", ["rev-parse", "--git-dir"], {
    cwd: root,
  });
  return path.resolve(root, stdout.trim());
}

function shim() {
  return `#!/bin/sh
# generated by han.sip/pasang.mjs — jalankan lagi kalau file ini hilang
root="$(git rev-parse --show-toplevel)" || exit 2
exec node "$root/${MARKER}"
`;
}

async function main() {
  const check = process.argv.includes("--check");
  const root = await toplevel();
  const dest = path.join(await gitDir(root), "hooks", "pre-commit");

  if (check) {
    let body = "";
    try {
      body = await readFile(dest, "utf8");
    } catch {
      console.error("han.sip pasang: hook belum ada");
      process.exit(1);
    }
    if (!body.includes(MARKER)) {
      console.error("han.sip pasang: hook bukan punya kita");
      process.exit(1);
    }
    console.log("han.sip pasang: sip.");
    process.exit(0);
  }

  await mkdir(path.dirname(dest), { recursive: true });
  await writeFile(dest, shim(), { encoding: "utf8", mode: 0o755 });
  await chmod(dest, 0o755);
  console.log("han.sip pasang: pre-commit terpasang.");
}

main().catch((err) => {
  console.error("han.sip pasang:", err.message);
  process.exit(2);
});
